import { Box } from '@chakra-ui/react';
import type { GetStaticProps, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Character, GetCharacterResutls } from '../types/types';

const Home: NextPage<{ characters: Character[] }> = ({ characters }: any) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			Checking
			{characters.map((characters: Character) => {
				return (
					<Box p={4} key={characters.id}>
						{characters.name}
						<Image
							src={characters.image}
							alt={characters.name}
							width='200px'
							height='200px'
						/>
						;
					</Box>
				);
			})}
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
	const res = await fetch('https://rickandmortyapi.com/api/character');
	const { results }: GetCharacterResutls = await res.json();

	return {
		props: {
			characters: results,
		},
	};
};
